### ISSUE TITLE
g722.pcap

### ISSUE THREAD

**Issue by StefanoGasco** [saghul/sipp-scenarios#6]
Hello,

I'm just learning to use SIPp and your repo is extremely helpful.
I was wondering - how do you generate a .pcap file with an encoded audio (i.e. g722.pcap with mission impossible sound track)? I've been messing around for a while with wireshark and at this point doesn't seem the correct tool.

Thank you!

**Comment by jarrar** [comment]
Thanks.

I have not done that in many years, so dont recall.

Jarrar

**Comment by StefanoGasco** [comment]
An easy way I found to encode any audio is to use an external softphone (i.e. X-Lite) and force the desired codecs; execute a call with the desired audio and trace it with WireShark; filter the RTP stream in both direction and export the RTP stream as a .pcap.

Thank you again for the repo
